In [1]:
from sklearn.decomposition import TruncatedSVD

In [2]:
import numpy as np

In [22]:
a = np.array([[0,2,0,3],[-2,0,1,0],[0,-1,0,1],[-3,0,-1,0]])

In [23]:
svd = TruncatedSVD(n_components=3, n_iter=7, random_state=42)

In [24]:
svd.fit(a)

TruncatedSVD(algorithm='randomized', n_components=3, n_iter=7,
       random_state=42, tol=0.0)

In [25]:
svd.components_

array([[ -9.95959314e-01,  -7.97633917e-17,  -8.98055953e-02,
          0.00000000e+00],
       [  0.00000000e+00,   5.25731112e-01,  -4.44089210e-16,
          8.50650808e-01],
       [ -8.98055953e-02,   8.84589570e-16,   9.95959314e-01,
         -0.00000000e+00]])

In [26]:
np.linalg.svd(a)

(array([[  0.00000000e+00,  -9.95959314e-01,   8.98055953e-02,
          -2.77555756e-16],
        [  5.25731112e-01,   2.40775052e-16,  -1.95797359e-17,
          -8.50650808e-01],
        [  0.00000000e+00,  -8.98055953e-02,  -9.95959314e-01,
           0.00000000e+00],
        [  8.50650808e-01,  -8.29266323e-17,   8.79431260e-18,
           5.25731112e-01]]),
 array([ 3.61803399,  3.61803399,  1.38196601,  1.38196601]),
 array([[-0.99595931,  0.        , -0.0898056 ,  0.        ],
        [ 0.        , -0.52573111,  0.        , -0.85065081],
        [-0.        ,  0.85065081,  0.        , -0.52573111],
        [ 0.0898056 ,  0.        , -0.99595931,  0.        ]]))